# Makefile provided by stackoverflow user revolutionary and modified for our purposes
# https://stackoverflow.com/questions/48568966/using-c-boost-in-a-makefile
BOOST_ROOT := C:/Program\ Files/Boost/boost_1_62_0/
BOOST_INC := ${BOOST_ROOT}/include

Zipper: Zipper.cpp
	g++ -L${BOOST_ROOT} Zipper.cpp -o Zipper.o