
name: Utility Tests
on: [push]
jobs:
  Run-Util-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libboost-all-dev -y; sudo apt install libzip-dev -y;
      - run: |
          cd tests
          make obj/UtilityTests.test